### PR TITLE
Lab1

### PR DESCRIPTION
**Pull request by AdamK42**
@danilasokratov  I believe my lab is also done. My apologies for having it done so late, I've been rather ill that last few days and have not been able to think very well. Hopefully Shifeng gets back to you soon on how to view the pull requests.

### CODE REVIEW

**Comment by AdamK42** [comment]
@danilasokratov, I just saw that we are also supposed to print an html version. Is that any more readable on github?

**Comment by AdamK42** [comment]
I left this comment on your repo too, but try opening the .html file in your browser. It looks nicely formatted for me anyway.

**Comment by danilasokratov** [comment]
Okay, thank you! I'll check it out in a couple of hours.

**Comment by danilasokratov** [comment]
@AdamK42 I think your lab looks solid! If I were to give a suggestion, I think the "discrete sigmas" section is written in a confusing way. I don't fully understand this: 

"This means that an upper and lower cases, we know there will be an upper and lower probability to of any measurement, and an upper and lower sigma value. This means that if we hit these probabilities or sigma values, we can say that we have hit a maximally sure result."

Are you talking about outliers in the distribution? I'm not exactly sure what your point here is. It seems to me that you are answering the "implications to experiment" part. Here is how I understand this section:
"Due to the nature of the binomial distribution, there will be outliers with the upper end having higher probabilities of measurement and lower end having lower probabilities of measurement (not sure if I am understanding this correctly). If experimental measurement results in these outliers, then it is most likely to be a measurement."

Is this interpretation correct?

I think the flow of the rest of your code is very intuitive and well explained. Good job!

**Comment by AdamK42** [comment]
@danilasokratov Your interpretation was correct, I think I was just thinking faster then I can type and some words got skipped. Is this more clear?

**Comment by danilasokratov** [comment]
@AdamK42 I like this a lot better!

**Comment by AdamK42** [comment]
@sfzhu This is my submission for the Lab 1 assignment. There should be a python notebook and a .html file in the folder physics-434/lab1/

**Comment by sfzhu** [comment]
5 sigma actually corresponds to  1 - 4.999999999970176, so it should be 5sigma -> 1 -  4.999999999970176. According to the way norm.ppf is setup, it's norm.ppf(1 - p).

Need to finish 3 A-C.

Need to explain clearly of your Hypothetical question.

**Pull request merged**
