### PR TITLE
Lab2

### PR DESCRIPTION
**Pull request by AdamK42**
@danilasokratov I think this is done. I am gonna go back tomorrow and standardize the way that I am doing my summed/convolved distributions so that it is all consistent with what we did Thursday. Please let me know of what you think of my answer for 3B and 3C, I'm still not entirely convinced I did them right.

### CODE REVIEW

**Comment by danilasokratov** [comment]
@AdamK42 I'm not sure if 3c is correct. Since I can't really play around with python, could you tell me what you get when you change the value of signal? Try the value you got from 4B, since if your method works, it should give you 5 sigma as a result.

**Comment by danilasokratov** [comment]
@AdamK42 I have not taken a close look at the rest of your code yet, will do so in a bit.

**Comment by danilasokratov** [comment]
@AdamK42 I think it would be nice if you would discuss a bit more in sections where the lab mentions "show x" how that changes. For example, in 1B, you've shown it on the plots, but the plots look almost identical. A small description at the end of the section would be helpful.

In part 1D, I ended up getting a sigma of ~3. You can take a look at my code if that helps. I essentially re-made the probability distribution, scaling the parameter (mu, I think) by the number of days. After that, both my probability and my sigma behaved well.

If you have the time, in part 2B you could look for a point where the distribution begins approaching a Gaussian a bit closer. Mine ended up happening at ~15, so I'm a bit surprised that yours isn't doing so at 16. We also seem to have differences in how our distributions look — yours are cutting off at zero, whereas in mine the mean shifted a bit and the distributions smoothened as I increased the number of intervals. Not sure why this difference, however.

Part 4 seems solid. Tell me how playing around with part 3 goes.
Also, this isn't important, but I think the distribution is a Gaussian, not a Guassian. I don't know if they take off points for misspelling (I hope not), just wanted to mention.

**Comment by AdamK42** [comment]
I haven't been able to change most of what you wanted, but I'm not sure what to do. From what I can tell, you and I did the same thing for 1D, its just that mine keeps getting rounded and I don't know how to stop that from happening. For part 2B, I don't think the mean should be shifting since there is no mechanism for that in the Rayleigh distribution according to [this documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rayleigh.html?highlight=stats%20rayleigh#scipy.stats.rayleigh). For my answer to 3C, I'm still not fully convinced this gets me the right answer, it is within the ball park though, and it is consistent with how the slides in class went as well as my answer to part 4.

**Comment by AdamK42** [comment]
@sfzhu Lab 2 is finished.

**Comment by sfzhu** [comment]
Problem 2. We need to follow the same idea as the first problem, convolution is needed here. After re-scaling the x axis, we will get a distribution more and more like the normal distribution. You only changed the x range scale in your answers.

Problem 3 C. The code should be 
percentile = norm.cdf(signal, scale=width)
sigma = norm.ppf(percentile*pixels) (usually the value in the parenthesis is greater than 1, so use sigma = 1 - norm.ppf( 1 - (1 - percentile)*pixels), if the value inside the ppf function is still greater than 1, that means the value you are testing has a very large probability). Your answer for Problem 4 is correct.

**Pull request merged**
