### PR TITLE
Lab4

### PR DESCRIPTION
**Pull request by AdamK42**
@danilasokratov  I am done. I don't think I'm going to finish the lab, I super don't get the problem 2 data analysis. I kinda see what I can do with the images to get the most useful image, but I don't get what to do with that information or how to analyze that image.

### CODE REVIEW

**Comment by danilasokratov** [comment]
@AdamK42 It looks good. I don't know if I can explain much more about the last problem, as I am not completely sure how to finish it up. My understanding of getting a background for faint stars is that you want a signal that does not have periodic sources. I think you can subtract images from each other, and then average those results. This should get rid of all "constant" sources of signal, which faint stars should be. If you've gotten rid of all constant sources of signal, then you have your background. You can then compare the background to the images themselves — maybe subtract the background from each image individually? Then you should be left with just constant sources (maybe transients as well though), and then you can cast that into a 1d vector and do a histogram. It's a bit to do at this point, however. Good work.

**Comment by AdamK42** [comment]
@danilasokratov  I see what you are saying. Wouldn't subtracting the images just get us 200 x 200 pixels of 0? I'm probably to tired to understand what you mean, I don't think I care at this point honestly. Thanks for giving me something to think about tomorrow though!

**Comment by AdamK42** [comment]
@sfzhu This is done.

**Comment by sfzhu** [comment]
For Q1, you could add a plot of lambda - longitude.
For Q2, since you are looking for faint stars, you are looking at each image. Those stars way beyond 5 sigmas could be transient, so you could just look at those larger than 5 sigmas but not too large.

**Pull request merged**
